version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17    # Java 11에서 17로 변경

  pre_build:
    commands:
      - echo Build started on `date`
      - echo Starting pre-build phase...

  build:
    commands:
      - echo Building the application...
      - chmod +x ./gradlew
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying built files...
      - cp build/libs/*.jar ./application.jar

artifacts:
  files:
    - application.jar
    - scripts/**
    - appspec.yml
  discard-paths: no

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
